### PR TITLE
Add colorfull helper func to handle assertions

### PR DESCRIPTION
**Pull request by davesnx**
https://github.com/rafritts/bunit/pull/37

### CODE REVIEW

**Comment by davesnx** [comment]
Does it look good to you?

**Comment by rafritts** [comment]
Hey sorry!  I just now saw this.  I will 100% take a look at this when I get home from work.  Again, sorry about the super late response.

**Comment by davesnx** [comment]
Hey @rafritts, could you merge or close this one? 🗡 

Thanks!

**Comment by rafritts** [comment]
Sorry it took so long to merge this.

**Pull request merged**
